Repository RubricLab/maige, pull requests merged in 2023-11, with the labels that each got.

#44 Chore/refactor
  .env.example
  .eslintrc
  .eslintrc.js
  .vscode/settings.json
  app/api/stripe/generate-payment-link/route.ts
  app/api/webhook/github/route.ts
  app/api/webhook/stripe/route.ts
  app/components/Footer.tsx
  app/components/Header.tsx
  app/components/logos/Cal.tsx
  app/components/logos/Highlight.tsx
  app/components/logos/Precedent.tsx
  app/components/logos/Trigger.tsx
  app/env.mjs
  app/layout.tsx
  app/page.tsx
  app/success/page.tsx
  bun.lockb
  lib/agents/engineer.test.ts
  lib/agents/engineer.ts
  lib/agents/maige.ts
  lib/components/Footer.tsx
  lib/components/Header.tsx
  lib/components/logos/Cal.tsx
  lib/components/logos/Highlight.tsx
  lib/components/logos/Precedent.tsx
  lib/components/logos/Trigger.tsx
  lib/constants.ts
  lib/env.mjs
  lib/planetscale.ts
  lib/prisma.ts
  lib/stripe.ts
  lib/styles/globals.css
  lib/tests/engineer.test.ts
  lib/tools.ts
  lib/tools/comment.ts
  lib/tools/exec.ts
  lib/tools/github.ts
  lib/tools/label.ts
  lib/tools/updateInstructions.ts
  lib/types.ts
  lib/utils/github.ts
  lib/utils/index.ts
  lib/utils/payment.ts
  next.config.mjs
  package.json
  postcss.config.cjs
  prettier.config.cjs
  public/site.webmanifest
  tailwind.config.cjs
  tailwind.config.ts
  tsconfig.json
Labels: webhooks

#46 [MAR 12, 14, 26] - Query Codebase Tools
  .env.example
  .gitignore
  app/api/webhook/github/route.ts
  bun.lockb
  lib/agents/engineer.ts
  lib/agents/maige.ts
  lib/constants.ts
  lib/tools/codeSearch.ts
  lib/tools/updateInstructions.ts
  lib/utils/embeddings/cloneRepo.ts
  lib/utils/embeddings/db.ts
  lib/utils/embeddings/delete.ts
  lib/utils/embeddings/embed.ts
  lib/utils/embeddings/exists.ts
  lib/utils/embeddings/query.ts
  lib/utils/github.ts
  package.json
Labels: enhancement, webhooks

#49 Create Weaviate schema
  lib/utils/embeddings/setup.ts
  lib/utils/embeddings/setup/index.ts
  lib/utils/embeddings/setup/schema.ts
  package.json
Labels: enhancement, database
