Repository RubricLab/maige, pull requests merged in 2024-02, with the labels that each got.

#102 Webhooks
  app/[slug]/(base)/page.tsx
  app/api/webhook/github/route.ts
  bun.lockb
  lib/agents/maige.ts
  lib/types/index.ts
  lib/utils/github/handle/app-install.ts
  lib/utils/github/handle/app-uninstall.ts
  lib/utils/github/handle/app-updates.ts
  lib/utils/github/handle/index.ts
  lib/utils/github/handle/issues.ts
  lib/utils/github/handle/pull-requests.ts
  lib/utils/index.ts
  lib/utils/payment.ts
  lib/utils/prompt.ts
  package.json
  prisma/schema.prisma
Labels: webhooks

#109 Webhooks 2.0
  app/api/webhook/github/route.ts
  bun.lockb
  lib/agents/maige.ts
  lib/types/index.ts
  lib/utils/github/handle/app-install.ts
  lib/utils/github/handle/app-uninstall.ts
  lib/utils/github/handle/app-updates.ts
  lib/utils/github/handle/index.ts
  lib/utils/github/handle/issues.ts
  lib/utils/github/handle/pull-requests.ts
  lib/utils/index.ts
  lib/utils/payment.ts
  lib/utils/prompt.ts
  package.json
  prisma/schema.prisma
Labels: urgent, webhooks

#115 feat: scope usage to team and project level
  app/[slug]/(base)/usage/[[...metric]]/layout.tsx
  bun.lockb
  lib/agents/reviewer.ts
  lib/components/dashboard/Metrics/LogsView.tsx
  lib/components/dashboard/Metrics/TableWrapper.tsx
  lib/components/dashboard/Metrics/projectFilter.tsx
  lib/components/dashboard/Metrics/projectFilterWrapper.tsx
  lib/components/dashboard/Navigation/ProjectNav.tsx
  lib/components/ui/select.tsx
  lib/utils/github/handle/issues.ts
  package.json
  prisma/schema.prisma
Labels: urgent

#104 [WIP] eng/acc
  lib/agents/engineer.ts
  lib/agents/maige.ts
  lib/tools/dispatchEngineer.ts
  lib/utils/github.ts
Labels: enhancement

#116 Collaborators
  app/[slug]/(base)/settings/advanced/page.tsx
  app/[slug]/(base)/settings/billing/page.tsx
  app/[slug]/(base)/settings/layout.tsx
  app/[slug]/(base)/settings/members/page.tsx
  app/[slug]/(base)/settings/page.tsx
  app/[slug]/project/[projectId]/settings/page.tsx
  app/invite/[inviteId]/layout.tsx
  app/invite/[inviteId]/page.tsx
  bun.lockb
  lib/actions/create-invitation.ts
  lib/actions/create-membership.ts
  lib/actions/delete-invitation.ts
  lib/actions/delete-member.ts
  lib/components/CommandBar.tsx
  lib/components/dashboard/Feedback/FeedbackForm.tsx
  lib/components/dashboard/Navigation/MainNav.tsx
  lib/components/dashboard/Navigation/SettingsNav.tsx
  lib/components/dashboard/Settings/DeleteTeam.tsx
  lib/components/dashboard/Settings/ExistingMembers.tsx
  lib/components/dashboard/Settings/InviteDialog.tsx
  lib/components/dashboard/Settings/InviteForm.tsx
  lib/components/dashboard/Settings/PendingInvitations.tsx
  lib/components/dashboard/Settings/index.ts
  lib/components/dashboard/Team/AcceptInvite.tsx
  lib/components/ui/button.tsx
  lib/components/ui/dialog.tsx
  lib/components/ui/select.tsx
  lib/utils.ts
  package.json
  prisma/schema.prisma
Labels: enhancement, needs screenshot

#120 feat: logs ui and usage charts
  app/[slug]/(base)/usage/[[...metric]]/layout.tsx
  lib/agents/engineer.ts
  lib/agents/maige.ts
  lib/agents/reviewer.ts
  lib/components/dashboard/Metrics/Charts.tsx
  lib/components/dashboard/Metrics/CustomTable.tsx
  lib/components/dashboard/Metrics/LogsView.tsx
  lib/tools/dispatchReviewer.ts
Labels: urgent

#119 style: dashboard header slash and select
  lib/components/dashboard/Navigation/DashboardNavClient.tsx
  lib/components/dashboard/Navigation/ProjectSelect.tsx
  lib/components/dashboard/Navigation/TeamSelect.tsx
Labels: dashboard

#117 eng/acc
  .env.example
  app/api/agent/engineer/route.ts
  lib/agents/engineer.ts
  lib/agents/maige.ts
  lib/env.mjs
  lib/tests/engineer.test.ts
  lib/tools/dispatchEngineer.ts
  lib/utils/desyncedAgentCall.ts
  lib/utils/github.ts
  lib/utils/github/handle/issues.ts
Labels: enhancement, needs screenshot
